Repository doc-sys/docsys, pull requests merged in 2020-04, with the labels that each got.

#11 add Dockerfile & docker-compose.yaml
  Dockerfile
  docker-compose.yaml
Labels: enhancement

#16 fix links in README.md
  README.md
Labels: documentation

#18 added typescript support (in preparation of #14)
  .babelrc
  .dockerignore
  Dockerfile
  lib/.gitignore
  package-lock.json
  package.json
  src/index.ts
  tsconfig.json
Labels: enhancement, functionality

#17 fixing developement delay
  .eslintrc.json
  src/routes/documents.js
  src/routes/users.js
Labels: bug

#19 naming convention
  README.md
  docs/api_data.js
  docs/api_data.json
  docs/api_project.js
  docs/api_project.json
  src/app.js
  src/routes/documents.js
  src/routes/users.js
  src/storage/storagefile.ts
Labels: enhancement

#29 error handling and tests
  src/app.js
  src/helpers/error.ts
  src/routes/users.js
  tests/user.js
Labels: enhancement, functionality

#31 adding google storage
  package-lock.json
  package.json
  src/storage/adapters/google.ts
Labels: enhancement

#33 localstorage adapter
  src/storage/adapters/local.ts
  tests/storage.local.ts
Labels: enhancement, functionality

#34 fixing some minor problems
  .github/workflows/lint.yml
  src/app.js
  src/routes/admin.js
  src/storage/storagefile.ts
  tests/user.js
Labels: bug
